#!/usr/bin/env bash

tmpbg='/tmp/screen.png'
scrot -o "$tmpbg"
convert "$tmpbg" -scale 10% -scale 1000% -gravity center -matte "$tmpbg"
i3lock -i "$tmpbg"


# Add this script's path to i3 config. Use xautolock to auto lock the screen after 10 minutes of inactivity.
# bindsym $mod+Ctrl+l exec /bin/lock
# exec --no-startup-id xautolock -time 10 -locker lock

